version: '3.1'
services:
  stats-server:
    build: stats-service/service
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - STATS-SERVER-URL=http://localhost:9090


  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
