drop table if exists stats;
CREATE TABLE stats (
                               id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               app varchar(255) NOT NULL,
                               uri varchar(255) NOT NULL,
                               ip varchar(255) NOT NULL,
                               timestamp timestamp NOT NULL
);
